AWSTemplateFormatVersion: 2010-09-09
Description: |
  This template creates an Phonebook Application deployed on AWS Application Load Balancer with Auto Scaling and RDS
Parameters:
  
Metadata:
  
Mappings:
  
Conditions:
  
Resources:
LogicalID:
  Type: AWS::ElasticLoadBalancingV2::LoadBalancer
  Properties:
    IpAddressType: "String"
    LoadBalancerAttributes:
      LoadBalancerAttributes
    Name: "String"
    Scheme: "String"
    SecurityGroups:
      SecurityGroups
    SubnetMappings:
      SubnetMappings
    Subnets:
      Subnets
    Tags:
      Tags
    Type: "String"

Transform:
  
Outputs: