AWSTemplateFormatVersion: 2010-09-09
Description: |
  This template creates an Phonebook Application deployed on AWS Application Load Balancer with Auto Scaling and RDS
Parameters:
  
Metadata:
  
Mappings:
  
Conditions:
  
Resources:
  
Transform:
  
Outputs: