AWSTemplateFormatVersion: 2010-09-09
Description: |
  Cloudformation Template for kittens carousel static website deploy on s3 through cloudfront and route 53
Parameters:
  DomainName:
    Description: DNS Name of existing Amazon Route 53 hosted zone ex. ahmetdevops.link
    Type: AWS::Route53::HostedZone::Id
  KittensDomainName:
    Description: Full domain name for the App. ex. kittens.ahmetdevops.link
    Type: kittens.ahmetdevops.link
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)  
Resources:
  KittensBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: !Ref KittensDomainName
      WebsiteConfiguration:
        IndexDocument: index.html
  KittensBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref KittensBucket # Required
      PolicyDocument:
        Statement:
          - Sid: PublicReadforStaticWebsite
            Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Join ['', ['arn:aws:s3:::', !Ref 'KittensBucket', /*]]
  LogicalID
    Type: AWS::CertificateManager::Certificate
    Properties: 
      CertificateTransparencyLoggingPreference: ENABLED
      DomainName: !Ref KittensDomainName
      DomainValidationOptions: 
        - DomainValidationOption
      SubjectAlternativeNames: 
        - String
      Tags: 
        - Tag
      ValidationMethod: String

      
              
  
Outputs: